### PR TITLE
📝 Add data loader examples to cellxgene guide

### PR DESCRIPTION
**Pull request by Koncopd**
The dependencies are pretty heavy so i added the example as a code snippet in markdown.

### CODE REVIEW

**Comment by falexwolf** [comment]
Can you please make 2 subsections under "Train ML models" so that it both approaches are visually more balanced?

image

It'd also be really great to actually add the code snippet for MappedCollection so that people don't absolutely have to jump to the other guide.

**Comment by falexwolf** [comment]
(Otherwise, great! Thank you! 🙏)

**Comment by Koncopd** [comment]
Sorry, which subsections should be added?

**Comment by falexwolf** [comment]
There should be a subsection (1) that trains on the collection of h5ad

image

And a subsection (2) that trains on the tiledbsoma array store.

**Comment by falexwolf** [comment]
Whereever you do:

```
collection = ln.Collection.filter(name="cellxgene-census", version=census_version).one()
```

you can meanwhile do

```
collection = ln.Collection.get(name="cellxgene-census", version=census_version)
```

That's easier to read because a few users found the `.one()` confusing.

**Comment by Koncopd** [comment]
@falexwolf can i merge?

**Comment by falexwolf** [comment]
Something seems to be messed up with the sections all of a sudden? This wasn't the case earlier 🤔 

Did somebody update lndocs? Or did you change something?

image

**Comment by falexwolf** [comment]
This is how it looks on prod:

image

**Comment by falexwolf** [comment]
lndocs doesn't have a change for more than a week so it gotta be something in this PR or build env. 🤔

**Comment by Koncopd** [comment]
Hm, checking.

**Comment by falexwolf** [comment]
Building docs locally on main looks fine:

image

**Comment by falexwolf** [comment]
Great, it was the backticks. This fixed it.

So now it's just nitpicking about the exact wording. I'll make another commit here to make the subsections read exactly the same

image

**Comment by falexwolf** [comment]
I'll finalize & merge this, @Koncopd! Thank you!

**Comment by falexwolf** [comment]
I'm discovering a tiny few more things that can be polished.

**Comment by Koncopd** [comment]
Ok!

**Comment by Koncopd** [comment]
Do we want to show this without hiding
image

**Comment by Koncopd** [comment]
Should it not be called "array store" properly
image

**Comment by falexwolf** [comment]
I went back and forth on this choice. I think the "array store" is the official precise language that we're using here at Lamin. But to ease users into building intuition that language sounded too complicated, so I simplified it to "concatenated array" in this overview doc.

So, it was a conscious choice playing through the experience of perceiving the whole doc.

**Pull request merged**
