### PR TITLE
Fix curate throwing an exception on instantiation

### PR DESCRIPTION
**Pull request by Zethson**
Fixes https://github.com/laminlabs/cellxgene-lamin/issues/69

### CODE REVIEW

**Comment by falexwolf** [comment]
:D

**Comment by falexwolf** [comment]
This is great!

Just one small thing.

We've historically used `bt.settings.organism` to build bad solutions, and so @sunnyosun & I agreed to eliminate it everywhere in the docs.

If a user wants it, they can still use it, but it's nothing we advocate so that also users write code that's locally scoped.

Can you please rewrite this without using the global setting? I hope it's just 2 lines to change. If it's more effort, then there might be a scoping problem.

image

**Comment by Zethson** [comment]
Ahh I was wondering about that. Sure, should be easy!

**Comment by falexwolf** [comment]
Thanks, Lukas!

**Pull request merged**
